### ISSUE TITLE
Using DATA_DIR on charts locally with k3d

### ISSUE THREAD

**Issue by AyliD** [localstack/helm-charts#49]
Every time my localstack pod crashes i'm loosing all secrets created before.
I would like to use my own local directory as DATA_DIR for persistency.
Seems like that use-case is working on docker-compose, but couldn't find it in helm chart.
Seems like in helm charts there is a need for PVC setup, which i dont have since running on macos k3d.

Is there a way to get persistency for my use case? if not, how do one use init-scripts to create same secrets on each restart of the pod?

**Comment by LaikaN57** [comment]
Does https://github.com/localstack/helm-charts/pull/48 or https://github.com/localstack/helm-charts/pull/42 solve your issue here?

Seems like [this ConfigMap](https://github.com/localstack/helm-charts/pull/48/files?show-viewed-files=true&file-filters%5B%5D=#diff-300d510a99dbbba90569d89129cacea39c909277b80ac1ec7c4819df58b56de9R5-R13) is where you can do your intended workaround for now.

Also, what version of the chart are you running currently?

**Comment by alexrashed** [comment]
Hi @AyliD!
Could you give your config another try with the latest version and the features @LaikaN57 mentioned?
Thanks!

**Comment by alexrashed** [comment]
I'll close this issue for now. Please feel free to create a new issue if you are still having issues.
