### ISSUE TITLE
Unable to run specific services in localstack

### ISSUE THREAD

**Issue by AndreCbrera** [localstack/helm-charts#82]
I'm trying to run a specific set of services in LocalStack using the startServices parameter in the values.yaml file. However, despite specifying a comma-separated list of services, I'm still able to see all services in the /health endpoint.

Here's what I've done so far:

- Modified the startServices parameter in the values.yaml file to only include the services I want to run (e.g., startServices: "redis,rds,route53,sqs,sns,s3").
- Restarted the LocalStack deployment.
- Despite these steps, when I check the /health endpoint, I can still see all services listed.

![image](https://user-images.githubusercontent.com/38178990/232830586-889b885b-a3c6-40b5-a438-c8ec3a9ce223.png)

And this is the configuration:

![image](https://user-images.githubusercontent.com/38178990/232830752-05adbd46-2500-46a7-b513-1312caa2d5c3.png)

Can someone please help me troubleshoot this issue?

Thank you :smile:

**Comment by alexrashed** [comment]
Actually, since [1.0.0](https://github.com/localstack/localstack/releases/tag/v1.0.0), the `SERVICES` environment variable is only used to define the set of services which should be loaded (in an eager fashion) if `EAGER_SERVICE_LOADING` is enabled (more specifically since https://github.com/localstack/localstack/pull/6438).

This basically means that always all services are available, but they are _loaded_ on demand. You can make sure the services you are using are eager loaded if you set the `SERVICES` environment variable _and_ `EAGER_SERVICE_LOADING`.

**Comment by AndreCbrera** [comment]
I need setting this a EAGER_SERVICE_LOADING variable like extraEnvVars ?
what value does it need to have ? 1/0 true/false

Thank you for your help :smile:

**Comment by alexrashed** [comment]
Please check out our docs, it explains the different configuration values: https://docs.localstack.cloud/references/configuration/
I've also seen that your list of services contains some services which are only provided in LocalStack Pro (`rds`), and also a service which does not exist (`redis`, you might mean `elasticache` - which is also currently a Pro-only service).
If you want to use LocalStack Pro with this Helm chart, you currently have to manually set the image to the pro image (this will also be handled by #81) and add an `LOCALSTACK_API_KEY` as env var.
